Fixed incompatibility with newer TypeScript versions
Removed 'async' keyword, since it is not allowed with the 'abstract' keyword (Error TS1243).

The implementation is still clear from the method signature (Promise as return type).